var treeParams = {
  "Type I": {
    "angleChange": 30,
    "angleVaryProp": 0.4,
    "depth": 6,
    "largeAngle": 60,
    "largeAngleProb": 0.0,
    "lengthChange": 0.8,
    "lengthVaryProp": 0.2,
    "lengthWidth": 0.2,
    "maxDepth": 6,
    "splitProb": 0.9,
    "splitProbChange": 1.0,
    "widthChange": 0.9
  },
  "Type Ia": {
    "angleChange": 30,
    "angleVaryProp": 0.4,
    "depth": 6,
    "largeAngle": 60,
    "largeAngleProb": 0.0,
    "lengthChange": 0.8,
    "lengthVaryProp": 0.2,
    "lengthWidth": 0.2,
    "maxDepth": 6,
    "splitProb": 0.9,
    "splitProbChange": 0.9,
    "widthChange": 0.9
  },
  "Type Ib": {
    "angleChange": 30,
    "angleVaryProp": 0.4,
    "depth": 6,
    "largeAngle": 60,
    "largeAngleProb": 0.2,
    "lengthChange": 0.8,
    "lengthVaryProp": 0.2,
    "lengthWidth": 0.2,
    "maxDepth": 6,
    "splitProb": 0.9,
    "splitProbChange": 0.9,
    "widthChange": 0.9
  },
  "Type II": {
    "angleChange": 20,
    "angleVaryProp": 1.0,
    "depth": 4,
    "largeAngle": 60,
    "largeAngleProb": 0.0,
    "lengthChange": 0.5,
    "lengthVaryProp": 0.1,
    "lengthWidth": 0.1,
    "maxDepth": 4,
    "splitProb": 0.95,
    "splitProbChange": 1.0,
    "widthChange": 0.9
  },
  "Type IIa": {
    "angleChange": 20,
    "angleVaryProp": 1.0,
    "depth": 4,
    "largeAngle": 60,
    "largeAngleProb": 0.0,
    "lengthChange": 0.5,
    "lengthVaryProp": 0.1,
    "lengthWidth": 0.1,
    "maxDepth": 4,
    "splitProb": 0.95,
    "splitProbChange": 0.9,
    "widthChange": 0.9
  },
  "Type IIb": {
    "angleChange": 20,
    "angleVaryProp": 1.0,
    "depth": 4,
    "largeAngle": 60,
    "largeAngleProb": 0.2,
    "lengthChange": 0.5,
    "lengthVaryProp": 0.1,
    "lengthWidth": 0.1,
    "maxDepth": 4,
    "splitProb": 0.95,
    "splitProbChange": 0.9,
    "widthChange": 0.9
  }
};